### ISSUE TITLE
WS projects  - Mincut analysis on WS networks

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#147]
Mincut form has a tool bar with five buttons
B1-126: Automatic mincut analysis  (only active if result_id is provided by user)
proposed valves to shutoff are automaticly provided by alghoritm
1- Call gw_fct_mincut (passing feature_id, feature_type and result_id)

B2-123: Custom mincut analysis.  (only active if B1 it have been cliked one time at least)
valve status is changed one by one by user and proposed valves to shutoff are recalculated
1- Map tool is activated to select by user (one by one) valves. Each valve selected is inserted on mincut_result_valve_unaccess (valve_id, result_id)
2- Call gw_fct_mincut (passing feature_id, feature_type and result_id)

B3-121: Connec selector  (only if result_id is provided by user)
User selects with map tool connec_id from all layers of connec. 
1- delete * from anl_mincut_connec
2- Insert into anl_mincut_connec all selected connecs
3- Call gw_fct_mincut_result_cat(result_id)

B4-122: Hydrometer selector (only if result_id is provided by user)
User selects hydrometer_id from hydrometer table
1- delete * from anl_mincut_hydrometer
2- Insert into anl_mincut_hydrometer all selected hydrometers
3- Call gw_fct_mincut_result_cat(result_id)

B5-99: Config

The rest of the fields of form of mincut must be updated on the fields on form

To prevent conlficts against diferent results:
- 1 Identify if there is a temporal colision (doing or planified), Add new field on status table and manage it as integer values (1-planified 2-ongoing, 3-executed)
- 2) If 2.1 is yes make a new mincut_Valve_analytics with closed valves of 1 and closed valves of 2
- 3) If result of 2.2 (pipes afected) is equal than the result of 1 and 2 by separate RAISE NOTICE: THERE IS AN OTHER MINCUT PLANIFIED AT SAME TIME BUT THERE IS NOT CONFLICT INTERACTING WITH IT.
- 4 If result (pipes afected) of 2.2 is more than the result of 1 and 2 by separate  RAISE WARNING: THERE IS A CONFLICT WITH ANOTHER MINCUT (RESULT_ID = ). PLEASES REVIEW YOUR ANALYSIS

**Comment by daviderill** [comment]
Issue duplicated in #178

**Comment by daviderill** [comment]
Close in #202
