### ISSUE TITLE
Node, Arc insert buttons (B1,B2)

### ISSUE THREAD

**Issue by bbrzepka** [Giswater/giswater_qgis_plugin#159]
Inserting the point using the button with drop down menu wih different system node_type available.
Work flow:

1. Activate the layer to which belong the type of node. DONE

2. Activate layer editing. DONE

3. User inserts the node on the map. DONE

4. Form is showed. DONE

5. Before enable edition python must validate the node topology and show to user (if proceed) this message box:

6. Check if node is over node (v_edit_node):
Get state of intersected node
Ask question:
We have detected you are trying to insert one node over another node with state (selected state). Remember that:
- In case of old or new node are on state=0, you are allowed to insert new one, because state 0 has not topology rules. 
- In the rest of cases, remember that the state topology rules of Giswater only enables one node with the same state at the same position. 
Would you like to continue?

Execute the normal process of the insertion node
Check parameter config.node_proximity

7.  Check if node is over arc (v_edit_arc):
Get state of intersected arc
Ask question:
### We have detected you are trying to divide an arc with state (selected state). Remeber that
- In case of arc has state=0, you are allowed to insert a new node, because state 0 has not topology rules, and as a result arc will not breaked.
- In case of arc has state =1,  only nodes with state=1 can be part of node1 or node2 from arc. If the new node has state=0 or state=2 arc will not breaked
- In case of arc has state = 2,  nodes with state =1 or state=2 are enabled. If the new node has state=0 arc will not breaked
Would you like to continue?

Execute The normal process of insertion node and after the insertion execute gw_fct_node2arc ('node_id) function
Check parameter config.node2arc

6. End

**Comment by daviderill** [comment]
Code it's working in initGui, but it should be moved to project_read
