### ISSUE TITLE
New psector buttom (B45)

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#170]
The goal of this button is to create a new psector with to planify new alternatives on network
(Before start we need to armonize the names of the objects of the form:
label_
btn_
chk_
tbl_

When user click on buttom:

1) plan_psector layers is active layer and toggled on edition
2) User must draw the polygon geometry
3) Form plan_psector.ui is showed
4) User fill data
	GENERAL: 
	(only psector_id is needed)
	table: plan_psector
	NETWORK ELEMENTS 
	(arc & node)
	Planified
	Add:  Map tool to choose arc/node and insert id into plan_psector_x_arc(node) with state=2
	Delete: Delete row from plan_psector_x_arc(node)
	Deprecated:
	Add:  Map tool to choose arc/node and insert id into plan_psector_x_arc(node) with state=1
	Delete: Delete row from plan_psector_x_arc(node)
	By clicking OK the parameter of config_vdefault (psector_vdefault)=(psector_id)

5) Later user can complete data of form and modify the psector geometry
	BUGDET
	Diferent calling parameters
	Only 3 editable fields
		other
		gexpenses
		vat
	By inserting data on this 3 fields, refresh date on form
	The rest views (no enabled to edit)
	OTHER
	Table: plan_psector
	By clicking OK the parameter of config_vdefault (psector_vdefault)=(psector_id)

**Comment by daviderill** [comment]
Close by #182
