### ISSUE TITLE
Go2epa buttom (B23)

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#173]
The goal of this buttom is copy the functionalities of Giswater file manager ui. To do this:

WS – By clicking B23 calling ws_file_manager_ui
UD – By clicking B23 calling ud_file_manager_ui

The submenus are:
(ws/ud) multisector_selector.ui
(ud)
	 ud_options.ui  (table inp_options)
	 ud_times.ui (table inp_times)
(ws)
	 ws_options.ui  (table inp_options)
	 ws_times.ui (table inp_times)

There are little diferences on UD forms againsts Giswater 2.1 forms
	- dissapear to export subcatchments geometry
	- dissapear raingage buttom
	- Times have been moved from options to a new form
        - Hydrology selector is moved from options to file manager

**Comment by daviderill** [comment]
Close in #186
