### ISSUE TITLE
Add plan estimate functionality (B38, B49)

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#183]
The goal of this issue is to calculate the cost of the network elements with data extracted from: v_edit_node, v_edit_arc, cat_arc, cat_soil, cat_pavement, price_compost, plan_arc_x_pavement, and filtered by only planified (or not)

1) Context
Toobar: masterp
Buttoms: 
B38 calling plan_estimate_result_new.ui  (to execute new result)
B49 calling plan_estimate_result_selector.ui (to show filter the results)

2) After click on calculate of plan_result_new.ui:
-2.1) Call the function of postgresql: gw_fct_plan_estimate_result('result_id', 'coefficient','only_planified')
-2.2) Wait for return
-2.3) Refresh canvas

3) After update the combobox value of plan_estimate_result_selector.ui 
-3.1) Update value of table 'plan_selector_result'
-3.2) Refresh canvas

**Comment by daviderill** [comment]
Change widget result_id to QComboBox
Table: rpt_cat_result
Field: result_id
