### ISSUE TITLE
Two config buttoms (edit tool bar &  master tool bar)

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#184]
The goal of this issue is to harmonize the privileges of the user with the config buttom.
In order to do this:
1) New config buttom have been created (B98) 
2) The config.ui have been separated into two files
 - config_edit.ui (B98)
 - config_master.ui (B99)
3) Should be reconnected all the functions....

**Comment by daviderill** [comment]
Close by #187
