### ISSUE TITLE
Replace node (B44)

### ISSUE THREAD

**Issue by daviderill** [Giswater/giswater_qgis_plugin#191]
User select a node
Ask user a confirmation question:
Are you sure you want to replace selected node with a new one?
Execute SQL function: 'gw_fct_node_replace'
Parameters (2):
node_id: id of selected node
viewname: view name related with selected node
Wait for the SQL execution, refresh canvas and show a confirmation or error message

Functionality and code should be similar to B17 (delete node)

**Comment by daviderill** [comment]
Close by #192

**Comment by xtorret** [comment]
Show previous form (to select default values for state 0) and post form (feature inserted)

**Comment by daviderill** [comment]
Close in #269
