### ISSUE TITLE
WS, "node_tolerance" missing in config.

### ISSUE THREAD

**Issue by vicente-medina** [Giswater/giswater_qgis_plugin#20]
PostgreSQL result after point insert:

PostGIS error while adding features: ERROR:  column "node_tolerance" does not exist
    LINE 1: SELECT node_tolerance          FROM config

**Comment by vicente-medina** [comment]
It seems that the bug is located in the trigger:

gw_trg_node_proximity

Where the "node_tolerance" was referred. The issue is solved using "node_proximity" instead.

**Comment by daviderill** [comment]
Solved in 2d2312d846f56be1a47fb4160f6aa2122eb813ec
