### ISSUE TITLE
Add import visit csv file button

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#257]
Button to import csv file using an especific format from csv to visit-event metodology.

**Comment by xtorret** [comment]
The goal of this functionality is to import into Giswater database a csv file with information about visits of UD networks (on 2.1 version)

1) Call form: ud_om_add_visit_file.ui 
2) User choose visitcat_id (SELECT DISTINCT short_descript FROM om_visit_cat) (2*)
3) User choose feature type (ONLY TWO VALUES (ARC/NODE) (3*)
4) User choose file
5) By clicking ok:
  5.1 File is imported into database as temp_om_visit_arc / node  (3*) table (with new id pk)
  5.2 Function gw_fct_sbd_om_visit(visitcat_id, feature_type) is called where visitcat is

**Comment by daviderill** [comment]
Close in #285
