### ISSUE TITLE
Custom forms - tab O&M: open visit, new visit

### ISSUE THREAD

**Issue by daviderill** [Giswater/giswater_qgis_plugin#299]

**Comment by luipir** [comment]
@daviderill custom forms? is it related with Visits?

**Comment by luipir** [comment]
@daviderill could you add some more detailed description about what to do? I'll try to infer what to do from this description.
"se trata de llamar desde los formularios de node, arc, connec a los botones que has programado
Se llaman desde la pestaña 'O&M'
Lo que tienes que hacer es muy parecido a lo que se hace en la pestaña 'Document'
Mira por ejemplo la función manage_document del módulo parent_init.py

**Comment by luipir** [comment]
looking for node,arc and connec forms to link to Document management

**Comment by luipir** [comment]
@daviderill @xtorret Just starting the project connected to db I used to create AddVisit, I receive the following erro: 
"relation "ws_data.audit_check_project" does not exist
LINE 2: INSERT INTO "ws_data".audit_check_project (table_schema, tab..."
Seems related with some latest DB changes. How can I remain aligned with the DB structure?

**Comment by luipir** [comment]
@daviderill @xtorret please test it

**Comment by daviderill** [comment]
Close in #357
