### ISSUE TITLE
Reordering config buttons

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#323]
The goal of this issue is to put in order the config buttons. To do that_
1- New config om button ( on om tool bar, config_om.ui, icons 96(WS) 97(UD)) with values visicat_vdefault & eventcat_vdefault
2- New values on config edit button: statetype_vdefault, pavcat_vdefault, ownercat_vdefault , soilcat_vdefault, sector_default, presszone_vdefault
3- New values on ws.config edit button, for each system_node_type on value 
4- Delete value of visicat_vdefault (in fact moved to om config button)
5- Remove tab search & tab other on config master

**Comment by daviderill** [comment]
Config edit - Add 'state_type'
Config edit - Tab WS: Add value defaults

**Comment by xtorret** [comment]
New parameters to manage on master config form:
psector_scale_vdefault
psector_rotation_vdefault
psector_gexpenses_vdefault
psector_vat_vdefault
psector_other_vdefault

**Comment by daviderill** [comment]
@edgarfuste I've just closed this issue and his branch.
Continue working in #341
