### ISSUE TITLE
Add new action switch_arc_id on ws node forms

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#326]
Add new action on the toolbars of WS node forms

Previous:
1) Forms are ready to use on dev3/ui_init
2) Function gw_fct_edit_node_switch_arc_id (dev3/sql/ws/fct)

By clicking button 
1) execute function gw_fct_edit_node_switch_arc_id passing the value of node_id
2) Refresh form

**Comment by daviderill** [comment]
We will have to add a new answer to the current question in 'check_topology_arc'
