### ISSUE TITLE
Enhance read project function

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#328]
When qgis project is loaded, this function will do:
1) Look for audit_cat_table and identify into the project all the layers with qgis_criticity=3
   - If result = 0 
            Dissable plugin
   - elsif result < select count(*) from audit_cat_table where qgis_criticity=3
            Dissable plugin
            Show all id from audit_cat_table where qgs_criticity=3 and not exists on qgis project
   - elsif result = select count(*) from audit_cat_table where qgis_criticity=3
            Enable plugin
2) Look for audit cat_table (qgis_role_context ) and indentify in function of role of user if table exists on project. If not exists, show table_id - qgis_criticity - qgis_message

**Comment by albertbofill** [comment]
Updated:

Read all the layers (using db table name) that are loaded in Qgis project and store it on  audit_project.table_id.
**Then use the _audit_project_ function and SHOW MESSAGE TO THE USER if result**

- =0 
Everything OK. All the layers in this project for the current role are loaded

- -1
It seems that this is a Giswater project but, to enable the plugin you need to load this layers...
_(SELECT * FROM audit_project WHERE criticity=3 AND enabled=FALSE AND audit_type=1)_

- n
There are 'n' tables that must be loaded on Qgis project
_(SELECT * FROM audit_project WHERE enabled=FALSE AND audit_type=1)_
