### ISSUE TITLE
Add tab relations on WS node/arc and UD arc forms

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#336]
1) Add tab relations on WS node/arc and UD arc forms as ws_man_junction, ws_man_pipe and ud_man_conduit examples (@edgarfuste )
2) Make the  v_ui_arc_relations & v_ui_node_relations views (@bbrzepka )
3) Relate the tbl_relations to v_ui_arc_relations & v_ui_node_relations views (@nestorip) 
    a) Connect the table view
    b) if there is no data -> Put hidden the tab
    c) If there is data -> Connect the element with the own form if user make double click on the row. For nodes relations must be nodes but for arcs, relations must be nodes/connecs/gullys
4) Put hidden the tab scada for all forms (@nestorip)

**Comment by daviderill** [comment]
TODO:
c) If there is data -> Connect the element with the own form if user make double click on the row. For nodes relations must be nodes but for arcs, relations must be nodes/connecs/gullys

**Comment by daviderill** [comment]
Close in #344
