### ISSUE TITLE
Enhance message for arc_divide and for insert node buttons

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#338]
**When the arc_divide button is executed, it is necessary:**
      1) Modify the message saying (for WS projects) that the value of the arc_id field, if exists, will be deleted
      2) In case of projects ws, before shooting the function you must do a UPDATE SET node arc_id = NULL WHERE node_id = clicked ...

**When inserting a node insert (WS):**
Use a check or another button to manage to not break. If it's clicked, find the arc_id value and put it in the form in the field of arc_id.     After this insert process, can we get the return of the arc_divide function, in case it has been executed?
0 - It's done well
1-n There are XX connects that could not be reconnected. Make them by hand
999 The division of the arc has not been made. Clear the value of the arc_id parameter before if you want to divide the arc

**Comment by nestorip** [comment]
Add new action on the toolbars of WS node forms

Previous:

Forms are ready to use on dev3/ui_init
Function gw_fct_edit_node_switch_arc_id (dev3/sql/ws/fct)
By clicking button

execute function gw_fct_edit_node_switch_arc_id passing the value of node_id
Refresh form
