### ISSUE TITLE
New toolbar 'utils'

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#341]

**Comment by daviderill** [comment]
New toolbar 'utils' always visible for everyone except 'basic' users
- Topology tools (button 19)
- Config (new button)
- Giswater (button 36)
- Check project (new button from #328)

**Comment by xtorret** [comment]
Add new paramaters on config button
**config-admin-review (table config_param_system)**
_-- ud
rev_arc_y1_tol
rev_arc_y2_tol
rev_arc_geom1_tol
rev_arc_geom2_tol
rev_nod_telev_tol
rev_nod_ymax_tol
rev_nod_geom1_tol
rev_nod_geom2_tol
rev_con_y1_tol
rev_con_y2_tol
rev_con_geom1_tol
rev_con_geom2_tol
rev_gul_topelev_tol
rev_gul_ymax_tol
rev_gul_sandbox_tol
rev_gul_geom1_tol
rev_gul_geom2_tol
rev_gul_units_tol
-- ws
rev_nod_elev_tol
rev_nod_depth_tol_
All of them are float, in exception of rev_gul_units_tol, that is integer

**config-epa: (tabla config_param_user)**
-- ud
_epa_outfall_type_vdefault
epa_conduit_q0_vdefault
epa_junction_y0_vdefault
epa_rgage_scf_vdefault_

**Comment by daviderill** [comment]
Close in #354
