### ISSUE TITLE
Call audit_check_data() functions

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#350]
**BUTTON B38**
Before call gw_fct_plan result (text, integer, double precision, text) call gw_fct_plan_audit_check_data(result_type) and:
If the function returns 0 everything is ok and you can call gw_fct_plan result
If the function returns more than (n), you must display a message: It is not possible to execute the economic result. There are (n) or more errors on your project. Review it!
See details:
    if result_type=1 then: select table_id, column_id, error_message FROM audit_check_data where fprocesscat_id=15 AND enabled is false (reposicio)
    if result_type=2 then: select table_id, column_id, error_message FROM audit_check_data where fprocesscat_id=16 AND enabled is false (rehab)

**BUTTONS B23**
IF the new check on form 'only_check' is dissabled THEN
  Call java (as is)
ELSIF  'only_check' is enabled THEN
  Call gw_fct_pg2epa('result_id', true)
     If the function returns 0 = Data is ok.  'You can try to generater the INP file'
     If the function returns more than (n), you must display a message: It is not possible to execute the epa model. There are (n) or more errors on your project. Review it!
See details: select table_id, column_id, error_message FROM audit_check_data where fprocesscat_id = 14 AND result_id = result_id_var;

**Comment by daviderill** [comment]
@xtorret 
Button 23:
Boolean parameter should be true or false? Because in mail you say 'false'...
Now Python calls gw_fct_pg2epa('result_id', 'true')
If the function returns 0: Python doesn't show any message

**Comment by xtorret** [comment]
I repeat:
 if form check is true python call function (true)
If form check is false python call java, and java call function  (false)

**Comment by xtorret** [comment]
Take a look on new check on form file manager  (B23)
