### ISSUE TITLE
Replace topology toolbox form by toolbox form on utils bar and add new functions

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#361]
New functions to add:
_**EDIT**_
QGIS project - SELECT gw_fct_audit_check_project(1);
User value default parameters - SELECT gw_fct_audit_check_project(19);
Check mincut data  - SELECT gw_fct_edit_audit_check_data(25);
Check profile tool data  - SELECT gw_fct_edit_audit_check_data(26);

**_MASTER_**
Reconstruction prices audit check data - SELECT gw_fct_plan_audit_check_data(15);
Rehabilitation prices audit check data - SELECT gw_fct_plan_audit_check_data(16);
Arc multi-psector - SELECT gw_fct_plan_anl_topology(20);
Node multi-psector - SELECT gw_fct_plan_anl_topology(21);
Node orphan - SELECT gw_fct_plan_anl_topology(22);
Node duplicated - SELECT gw_fct_plan_anl_topology(23);
Arc no start-end node - SELECT gw_fct_plan_anl_topology(24);

**_ADMIN_**
Audit check schema data- SELECT gw_fct_audit_check_project(2);

For the whole functions, make an upsert on the selector_audit table. Upsert means:
delete from selector_audit where cur_user=current_user;
insert into selector_audit (fprocesscat_id, cur_user) VALUES (fprocesscat_id, current_user);

**Comment by daviderill** [comment]
@bbrzepka
Functions with SQL errors:
- Node topological consistency
- Arc no start-end node
- Audit check schema data

**Comment by daviderill** [comment]
@edgarfuste 
Mostrar/Ocultar pestanya UD/WS en funció del tipus de projecte

**Comment by daviderill** [comment]
Close in #380
