### ISSUE TITLE
Add a daily logger file

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#363]
Create a new variable on config_propoerties and (forms config-basic) to enable the debug mode of plugin. This means when enable on read project
-Look for giswater java software
-Call for check project function (1,2,3)
.....more checks
Show in unified way results for user
Enable copy-paste or somehing like this to make easy the traceability
When dissable: don't so nothing and don't show nothing to user

**Comment by daviderill** [comment]
Read project:
Header with process_id
Add a new line for every missing layer

go2epa:
Add a new line to indicate that a CSV file has been created
Generate this CSV file and open it automatically

**Comment by daviderill** [comment]
Close in #391
