### ISSUE TITLE
Python Error when selecting layers

### ISSUE THREAD

**Issue by tveinot** [Giswater/giswater_qgis_plugin#402]
Hello;
I am getting a python error when I select giswater layers;
An error occurred during execution of following code:
formOpen( _qgis_featureform_3_0, _qgis_layer_v_edit_man_source20161013122934199_0, _qgis_feature_20180306132401582)

Traceback (most recent call last):
  File "", line 1, in 
  File "", line 23, in formOpen
  File "", line 44, in __init__
  File "", line 73, in init_config_form
  File "C:\Users\tveinot\.qgis2\python\plugins\giswater\utils_giswater.py", line 113, in getWidgetText
    widget = _dialog.findChild(QWidget, widget)
RuntimeError: wrapped C/C++ object of type QgsAttributeForm has been deleted

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.18.17 'Las Palmas', 98e769f70e

Using the test dataset the tools seem to work otherwise but the error stops me as I move from layer to layer editing.

**Comment by daviderill** [comment]
Hi,
Thanks for opening an issue reporting this situation.
Which version of the plugin are you using exactly?
Did it happen just one time, or always?
I see you use 2.18.17, but have you installed also QGIS3?

**Comment by tveinot** [comment]
Yes I have installed QGIS3.0 and now I have a Python27 and Python36 running, but I am using 2.18.X ltr QGIS3 is for playing and exploring new features....
The plugin version I am running is 2.1_115 (newest one from the repository).
I have 2 PC's running this; one is my personal computer and the other is my work computer. Both machines have QGIS 2.18.x lrt and QGIS3 with both Python 27 and 36. Last night while doing some tinkering on my home PC I got the tool set working on the example data in QGIS 2.18.X ltr. Thinking I had it solved I tried the same technique on my work machine and it failed. When I click a layer (or close QGIS) that error comes up several times. The tools work regardless of the error but it does mean I have to close the boxes before I can continue. 
I originally thought it was an issue with my environment but conversations with the QGIS_List lead me to think it might be a bug in the plugin so I put in an issue report; but now I am back to thinking it is an issue with my environment.

**Comment by luipir** [comment]
more probably a not (correctly) removed event listener that refer to a widget already destroyed (e.g. closed). Can you setup a procedure to replicate it?

**Comment by tveinot** [comment]
QuickAttributes plugin causes an issue with giswater plugin; disabling it solved the issue. Sorry for the inconvenience.
I began to realize that the only real difference between my setups is that I have more plugins enabled on this one. I shut them all off and went through them 1 by 1 until the error came back. It seems the plugins work as long as the other is disabled.
