### ISSUE TITLE
Harmonize manager forms

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#426]
1) Capture signal 'rejected' (user clicks X button)
2) Replace buttons open / cancel for button close (as rpt result manager has)
3) Use double click to select one row for all form
4) Enable maximize button

The list of forms is:
- mincut manager
- om psector manager
- doc manager
- element manager
- rpt result manager
- plan psector manager
- price manager

Disable constraint of set dimensions for psector management forms

**Comment by daviderill** [comment]
@xtorret It's already done...

**Comment by xtorret** [comment]
@daviderill Did you test it?.  For list announced not works
