### ISSUE TITLE
Concatenate State into Network Search Plus

### ISSUE THREAD

**Issue by albertbofill** [Giswater/giswater_qgis_plugin#447]
Concatenate State (OBSOLETE, ON SERVICE, PLANIFIED) after CODE + FEATURE_TYPE while searching network elements on Search tool.
To show the string, not the number, we must add a new column on _v_edit_*_ or modifiy the existing column _state_ ?

**Comment by xtorret** [comment]
To do this @nestorip, use the new views created 
**v_ui_node, v_ui_arc, v_ui_connec, v_ui_gully**
The field state_name has the custom name of the state in spite of the integer code

**Comment by nestorip** [comment]
done with inner join
