### ISSUE TITLE
Enhance end feature button

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#469]
After click on accept button on form:
If (select * from v_ui_arc_x_relations where arc_id in(selection of user) and arc_state=1) is not null then
show on form workcat_end_list the table view of **select * from v_ui_arc_x_relations where arc_id in(selection of user) and arc_state=1**
The form must be clicable making zoom to the clicked row and showing form of feature
If user click cancel -> nothing to do
If user click ok -> 
update (or insert) on config_param_user the value of **edit_arc_downgrade_force** to true
make downgrade (select as is)
restore on config_param_user the user's value of **edit_arc_downgrade_force** to false

**Comment by daviderill** [comment]
Close in #491
