### ISSUE TITLE
Add Clear button to Search Workcat

### ISSUE THREAD

**Issue by albertbofill** [Giswater/giswater_qgis_plugin#484]
In search plus tool, when you use workcat search, the selected workcat polygon remain activated in QGIS map, maybe obstaculizating the view of the other elements.

If this happens, users only have one option to not visualize this layer: desactivate layer.

To solve this, searchplus tool, in workcat tab, need one new button to clear the selection of workcat, which is related to _selector_workcat_ table.

This button, called _Clear Workcat_, must delete the existing register in _selector_workcat_ table.

**Comment by daviderill** [comment]
Close in #494
