### ISSUE TITLE
Database auditor tool

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#554]
Tool with the goal to audit the project data schema:
**Compare with other schema:**
- tables
- views
- functions
- triggers
- sequences
- fk
- config_param_system variables
- audit_cat_param_user variables

**Other**
- system variables: sys_crm, sys_utils.....
- results of check data consistency

**Comment by haubourg** [comment]
@xtorret I think https://github.com/opengisch/pum provides some useful features for this kind of tasks
