### ISSUE TITLE
Visitcat id field on Add visit form

### ISSUE THREAD

**Issue by albertbofill** [Giswater/giswater_qgis_plugin#572]
Visitcat_id is not the same on Visit management form and Add Visit. 

For example, if I have visitcat_id=2 on visit management, I see visitcat_id=0 on Add visit. The relation isn't good.

Besides this error in the visualization, when I change the tab on Add visit, phyton shows an error message related to visitcat_id.

**Comment by edgarfuste** [comment]
Bug fix
