### ISSUE TITLE
New button info (on EPA toolbar)

### ISSUE THREAD

**Issue by xtorret** [Giswater/giswater_qgis_plugin#583]
Same button that info, same code but when calling getinfofromcoordinates from this button (on epa toolbar) new parameter must be showed.
@albertbofill  Could you design the new button?
@nestorip, the call is the same adding **"toolBar":"epa"**. In order to harmonize perharps we can put **"toolBar":"basic"** when the current info is used
SELECT ws_sample.gw_api_getinfofromcoordinates($${
		"client":{"device":9, "infoType":100, "lang":"ES"},
		"form":{},
		"feature":{},
		"data":{"activeLayer":"ve_node",
			"visibleLayer":["ve_node","ve_arc"],
                         "toolBar":"epa"
			"coordinates":{"epsg":25831, "xcoord":419204.96, "ycoord":4576509.27, "zoomRatio":1000}}}$$)

**Comment by albertbofill** [comment]
@xtorret okey, the same as the new info from plugin (icon 37) but related to EPA, isn't it?
