### ISSUE TITLE
WS/UD gw_fct_dma_update

### ISSUE THREAD

**Issue by vicente-medina** [Giswater/giswater_qgis_plugin#59]
Customer's request on 24/05/2016.

When dma is updated, dma_id of node, arc, connec & gully must be updated automaticlly if it's needed.

Overlap control between polygon it's needed

Commits done to the same branch than #58.

**Comment by daviderill** [comment]
@vicente-medina 
It would be nice to parametrize both functions in the same way that we have in gw_trg_edit_inp_arc.sql
Calling trigger with params and retrieving them with TG_ARGV[i]
