### ISSUE TITLE
i18n: Portuguese

### ISSUE THREAD

**Issue by daviderill** [Giswater/giswater_qgis_plugin#6]
Inside the folder i18n we will find translation files (*.ts)
We need to translate text to portuguese. The file to update is: Giswater_pt.ts (inside i18n folder)

**Comment by nexusbr** [comment]
Don't you think that we should have two Portuguse translations? One for Portugal-Portuguese and another Brazilian-Portuguese? So the extension should be something like _ptBr.ts

**Comment by daviderill** [comment]
Yes, we will create both translations like we have in Giswater
