### ISSUE TITLE
Refactor controller class

### ISSUE THREAD

**Issue by nestorip** [Giswater/giswater_qgis_plugin#697]
@daviderill detail issue please

**Comment by daviderill** [comment]
Controller class is getting too big and with too many different functionalities.
It manages database queries, log messages, support QGIS functions and specific Giswater SQL functions (like get_all_group_layers()So we want to split it in different files to isolate specific funcionalities. 
Names could be:
- db_manager.py: generic database functions
- logger_manager.py: generic log functions
- qgis_manager.py: generic QGIS functions- gw_manager.py: specific Giswater SQL functions and queries

Also utils_giswater should be renamed to:- widget_manager.py
All this files to be located in same folder, called 'lib', except gw_manager.py that should be placed in 'core' folder
