### ISSUE TITLE
Plugin fails to detect postgis connection

### ISSUE THREAD

**Issue by haubourg** [Giswater/giswater_qgis_plugin#716]
Hi @xtorret , 
We have been trying to test GIWATER 33 and all face the same issue, whatever the QGIS version we use.  I have been also checking many plugin versions from <3 to latest 3.3.010. 
We always end to `Connection failed. Please, check connection parameters`

![image](https://user-images.githubusercontent.com/1629853/68138977-a811ed80-ff29-11e9-8f34-86d9c9a98caf.png)

and the console raises only this:

```
Warning: QSqlDatabase: available drivers: QSQLITE QSPATIALITE
Warning: QSqlDatabasePrivate::removeDatabase: connection 'qt_sql_default_connection' is still in use, all queries will cease to work.
Warning: QSqlDatabasePrivate::addDatabase: duplicate connection name 'qt_sql_default_connection', old connection removed.
Warning: QSqlDatabase: QPSQL driver not loaded
Warning: QSqlDatabase: available drivers: QSQLITE QSPATIALITE
Warning: QSqlDatabasePrivate::removeDatabase: connection 'qt_sql_default_connection' is still in use, all queries will cease to work.
Warning: QSqlDatabasePrivate::addDatabase: duplicate connection name 'qt_sql_default_connection', old connection removed.
Warning: QSqlDatabase: QPSQL driver not loaded
Warning: QSqlDatabase: available drivers: QSQLITE QSPATIALITE
Warning: QSqlDatabasePrivate::removeDatabase: connection 'qt_sql_default_connection' is still in use, all queries will cease to work.
Warning: QSqlDatabasePrivate::addDatabase: duplicate connection name 'qt_sql_default_connection', old connection removed.
<class 'giswater_qgis_plugin.ui_manager.Readsql'>: mw_readsql
```

![image](https://user-images.githubusercontent.com/1629853/68139003-b3651900-ff29-11e9-980f-5e0015211f38.png)

Any idea how to cross this very first step? 

Regards

**Comment by xtorret** [comment]
I think problem may be that now only it's possible to use postGIS connections with not encrypted password (AS QGIS2). Can you check your PG connection?. We need to incorporate the way to manage encrypted connections (#717)

**Comment by haubourg** [comment]
> I think problem may be that now only it's possible to use postGIS connections with not encrypted password (AS QGIS2). Can you check your PG connection?. We need to incorporate the way to manage encrypted connections (#717)

mm, I use clear passwords. I'll test on windows maybe.

**Comment by daviderill** [comment]
> > I think problem may be that now only it's possible to use postGIS connections with not encrypted password (AS QGIS2). Can you check your PG connection?. We need to incorporate the way to manage encrypted connections (#717)
> 
> mm, I use clear passwords. I'll test on windows maybe.

Hi @haubourg,
Plugin generates a daily .log file located in the subfolder 'log' in plugin folder.
Can you please send us .log file that has been created to check these error-warning messages?
Can you also send printscreen of QGIS - About? 
And give us detail of your OS?
I remember I had some problems with QPSQL driver in Ubuntu some months ago and needed to upgrade it. 
Mail: support@bgeo.es

**Comment by haubourg** [comment]
>  I remember I had some problems with QPSQL driver in Ubuntu some months ago and needed to upgrade it.

This rings a bell!  Only one of us succeeded, and he was on BSD . cc @lbartoletti :)

here is the log:

[plugin_20191104.log](https://github.com/Giswater/giswater_qgis_plugin/files/3808433/plugin_20191104.log)

I am on ubuntu 18.04 

![image](https://user-images.githubusercontent.com/1629853/68199707-d8579b80-ffbe-11e9-8c64-2f765e7e5770.png)

and here are my qtsql details

![image](https://user-images.githubusercontent.com/1629853/68199825-0c32c100-ffbf-11e9-996f-cbdb9238ea2b.png)

**Comment by daviderill** [comment]
Confirmed that the problem is loading QPSQL driver. Do you have it?
>>> qgis.PyQt.QtSql.QSqlDatabase.drivers()

If not, it seems you only need to install this package:
>>> sudo apt install libqt5sql5-psql

More details:
https://gis.stackexchange.com/questions/291348/qpsql-driver-on-kubuntu-18-04

**Comment by haubourg** [comment]
indeed I installed the lib and now I have this :+1: 
```
qgis.PyQt.QtSql.QSqlDatabase.drivers()
['QSQLITE', 'QPSQL', 'QPSQL7', 'QSPATIALITE']
```

However, I still fail to connect 

the log is : 

```
05/11/2019 12:30:35 [INFO] - {/home/regis/APPS/GISWATER/v33/plugins/giswater_qgis_plugin/dao/controller.py | Line 92 (set_logger)}
Logger initialized

05/11/2019 12:30:35 [WARNING] - {/home/regis/APPS/GISWATER/v33/plugins/giswater_qgis_plugin/dao/controller.py | Line 256 (connect_to_database)}
fe_sendauth: no password supplied


05/11/2019 12:30:35 [WARNING] - {/home/regis/APPS/GISWATER/v33/plugins/giswater_qgis_plugin/dao/controller.py | Line 256 (connect_to_database)}
fe_sendauth: no password supplied


05/11/2019 12:30:35 [WARNING] - {/home/regis/APPS/GISWATER/v33/plugins/giswater_qgis_plugin/dao/controller.py | Line 256 (connect_to_database)}
fe_sendauth: no password supplied


05/11/2019 12:30:35 [WARNING] - {/home/regis/APPS/GISWATER/v33/plugins/giswater_qgis_plugin/dao/controller.py | Line 205 (get_layer_source_from_credentials)}
Error connecting to database (settings)

05/11/2019 12:30:35 [WARNING] - {/home/regis/APPS/GISWATER/v33/plugins/giswater_qgis_plugin/giswater.py | Line 742 (project_read)}
Error connecting to database

05/11/2019 12:30:35 [WARNING] - {/home/regis/APPS/GISWATER/v33/plugins/giswater_qgis_plugin/giswater.py | Line 743 (project_read)}
None
```

And my connection is configured this way 

![image](https://user-images.githubusercontent.com/1629853/68204669-d0045e00-ffc8-11e9-9bad-8b55cbaa72cc.png)

**Comment by daviderill** [comment]
Can you try to create another connection, preferably without SSL disabled and check again?
With an empty QGIS, can you open the only button available, tooltip 'Show info' (located in Plugins toolbar)?

**Comment by daviderill** [comment]
So, on Ubuntu is working already, and in Windows you still have the problem you commented?

**Comment by schorsch2** [comment]
It seems I have the same problem: I have created a database and can connect to it in qgis. If I use this connection in giswater, I get an error message: "WARNING Connection Failed. Please, check connection parameters" The log says:

`08/11/2019 11:08:04 [INFO] - {C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\giswater\dao\controller.py | Line 92 (set_logger)}
Logger initialized

08/11/2019 11:08:04 [WARNING] - {C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\giswater\dao\controller.py | Line 256 (connect_to_database)}
fe_sendauth: no password supplied

08/11/2019 11:09:54 [WARNING] - {C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\giswater\dao\controller.py | Line 256 (connect_to_database)}
fe_sendauth: no password supplied

08/11/2019 11:09:54 [WARNING] - {C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\giswater\dao\controller.py | Line 256 (connect_to_database)}
fe_sendauth: no password supplied

08/11/2019 11:09:54 [WARNING] - {C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\giswater\dao\controller.py | Line 256 (connect_to_database)}
fe_sendauth: no password supplied

08/11/2019 11:09:54 [WARNING] - {C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\giswater\dao\controller.py | Line 205 (get_layer_source_from_credentials)}
Error connecting to database (settings)

08/11/2019 11:09:54 [WARNING] - {C:/Users/wei/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\giswater\dao\controller.py | Line 256 (connect_to_database)}
fe_sendauth: no password supplied`

**Comment by schorsch2** [comment]
![dbconnection](https://user-images.githubusercontent.com/13661057/68468765-f6203d00-0218-11ea-8619-27e36522a0f5.png)
![giswaterconnection](https://user-images.githubusercontent.com/13661057/68468780-fcaeb480-0218-11ea-8ed8-aa0f411d9891.png)

**Comment by xtorret** [comment]
Nowadays only works saving ALL the connections parameters (including pasword) using the plain text option. We are enhancing this in order to don't save it

**Comment by schorsch2** [comment]
Even if I save the connection parameters with the qgis password manager, the same error messages follow. Is there another way to save the connection parameters?

**Comment by haubourg** [comment]
> Nowadays only works saving ALL the connections parameters (including pasword) using the plain text option. We are enhancing this in order to don't save it

I think it is unrelated. I tested with only plain test options.

**Comment by schorsch2** [comment]
The connection parameters must be stored in the register "basic" in the project itself, then the connection is recognized.
