### ISSUE TITLE
Versión vieja de Postgres? 

### ISSUE THREAD

**Issue by fdefranco** [Giswater/giswater_qgis_plugin#734]
Me aparece esta imagen en la consola y no puedo levantar mis viejos esquemas. 
Estoy retomando el uso. Soy de la época de que no era un plugin de QGIS! Ja. 
saludos 

![imagen](https://user-images.githubusercontent.com/60944823/74278911-b6299400-4cf8-11ea-93a8-f5ae5c94fd5f.png)

**Comment by xtorret** [comment]
Hola Federico,
Encantado de re-encontrar viejos usuarios.  Te respondo:

**Comment by fdefranco** [comment]
Perfecto. Gracias Xavi. 
Entiendo que ahora GisWater es sólo como plugin de QGIS. Qué buena noticia. 
Intento y seguimos en contacto. 
Abrazo
