### ISSUE TITLE
Shut down Qgis with composer

### ISSUE THREAD

**Issue by fdefranco** [Giswater/giswater_qgis_plugin#739]
Hola! Logré instalar todo y me puse a jugar con la demo para ir pegando las viejas tablas de los proyectos que tengo en Postgres 9.4 a la 9.5. 
Veo que hay algunas tablas que se modificaron. 
Lo que me resultó extraño fue que cada vez que quise ver perfiles o el composer de Qgis se me cerró. 
Adjunto foto. 
Abrazos
![Qgis_cierra](https://user-images.githubusercontent.com/60944823/74768890-2c357a00-5268-11ea-89a5-b711f9514108.png)

**Comment by xtorret** [comment]
Hola @fdefranco gracias por tu aportacion.
Lo tenemos localizado. El profile tool era una herramienta que funcionaba bien para QGIS2 pero en la migración a QGIS algo nos ha pasado Tenemos programado un refactor total del codigo de este boton. Plazo estimado: 2 meses.
