### ISSUE TITLE
"Flow trace" and "Flow exit" tools do not select anything

### ISSUE THREAD

**Issue by jdugge** [Giswater/giswater_qgis_plugin#741]
I have set up an `ud` demo project using QGIS 3.12, Giswater 3.3.036, PostgreSQL 110007 and PostGIS 2.5.3. The demo project schema and QGIS project are correctly generated, and after restarting QGIS and opening the project everything looks good: The conduits, manholes, streets, buildings etc. are visible and all relevant toolbars are shown.

However, when I select the "Flow trace" tool or the "Flow exit" tool and then click on a node, nothing happens, except for the tool deactivating itself. No arcs or nodes are selected, see attached video.

Am I using the tool wrong, or is something broken?

![2020-03-03_09-54-08](https://user-images.githubusercontent.com/2399255/75758883-f3e86e00-5d34-11ea-90e2-bc681a478c33.gif)

**Comment by xtorret** [comment]
Hello @jdugge. 
First of all thank you for use Giswater

**Comment by jdugge** [comment]
Thanks for getting back to me so quickly. Activating the Flowtrace analysis layers did the trick!

Sorry for the noise, and thanks for such an amazing tool!
