### ISSUE TITLE
Error al cargar el ejercicio de ejemplo

### ISSUE THREAD

**Issue by DavidJC40** [Giswater/giswater_qgis_plugin#768]
Buen día. Al momento de crear el ejercicio de ejemplo me sale este error, me podrían orientar en como resolverlo?  Gracias.
![Error Giswater](https://user-images.githubusercontent.com/69398715/89840182-3492b180-db35-11ea-8c09-a631b448e672.jpg)

**Comment by xtorret** [comment]
Hola,
¿Podriís darnos más pistas respecto a las versiones que estas usando?
Para reportar un bug, existe un protocolo. Te animanos a seguirlo
Saludos

**Comment by DavidJC40** [comment]
Buen día. Ya lo pude solucionar, gracias.
