### ISSUE TITLE
Can't start giswater plugin with QGIS  3.14

### ISSUE THREAD

**Issue by haubourg** [Giswater/giswater_qgis_plugin#771]
Hi there, 
I can successfully create a database schema with demo data and a project, but when loading the project, the plugin fails with : 

Tested with : 

- QGIS 3.14
- giswater plugin (from github releases) :  master / v3.4.018 / mv3.3.042 
- postgres 9.5 / postgis 2.5
................................

Here is the stacktrace. 

```python
Traceback (most recent call last):
              File "/usr/lib/python3/dist-packages/qgis/utils.py", line 359, in startPlugin
              plugins[packageName].initGui()
              File "/home/regis/.local/share/QGIS/QGIS3/profiles/GISWATER33/python/plugins/giswater/giswater.py", line 611, in initGui
              self.project_read(False)
              File "/home/regis/.local/share/QGIS/QGIS3/profiles/GISWATER33/python/plugins/giswater/giswater.py", line 857, in project_read
              if not self.manage_layers():
              File "/home/regis/.local/share/QGIS/QGIS3/profiles/GISWATER33/python/plugins/giswater/giswater.py", line 1035, in manage_layers
              status, result = self.check_project_result.populate_audit_check_project(layers, "true")
              File "/home/regis/.local/share/QGIS/QGIS3/profiles/GISWATER33/python/plugins/giswater/actions/check_project_result.py", line 37, in populate_audit_check_project
              layer_source['schema'] = layer_source['schema'].replace('"', '')
             AttributeError: 'NoneType' object has no attribute 'replace'
             
```

Any idea?

**Comment by albertbofill** [comment]
Hello,
Have you downloaded master-3.4 branch from giswater_qgis_plugin repository and master-3.4 from giswater_dbmodel repository?
I've just try (qgis3.10 and postgis 2.3) and everything works fine.

**Comment by haubourg** [comment]
@albertbofill I only downloaded the plugin from giswater_qgis_plugin only and used the plugin to instantiate a demo DB with demo dataset. 
I didn't see install instruction for the DB model so I guessed the plugin is the installer.

**Comment by albertbofill** [comment]
@haubourg that's true, there's no place in github with instructions about how to use this db model. This is because users usually downalod plugin from our public repository 'https://download.giswater.org/plugin/3.3/giswater.xml', where both repositories are merged and ready to be used.

It's simple, you just need to download giswater_dbmodel (mater-3.4) and add all the files from this folder into 'sql' folder in giswater plugin root.

This 3.4 version is brand new and, although we have a master version, we haven't released yet via our public repository. Soon everybody will be able to download it. 

If you want to try this last version you'll have to do how I said.

Thanks for your uderstanding.

**Comment by jcpiriou** [comment]
Hello Regis,
I agree with Albert, installation directly with the plugin is easy and works fine. Code and database can be checked after installation.
Best

**Comment by haubourg** [comment]
> @haubourg that's true, there's no place in github with instructions about how to use this db model. This is because users usually downalod plugin from our public repository 'https://download.giswater.org/plugin/3.3/giswater.xml', where both repositories are merged and ready to be used

Good to know and this deserves to be mentionned in the README . 

However I just tried with the repo and installed Version 3.3.042 . I still get the very same error. 
I'll try on Windows to check if this could be linked to my setup

**Comment by haubourg** [comment]
>  I agree with Albert, installation directly with the plugin is easy and works fine. Code and database can be checked after installation.

Well, I have several colleagues trying, I wouldn't say that yet ;-) . But let's polish this together

**Comment by haubourg** [comment]
Ok, using QGIS 3.14 + generating the database with demo data seems the issue. 
I manage to generate an empty working project in 3.10

**Comment by haubourg** [comment]
ok @albertbofill this is confirmed. giswater plugin does not work with 3.14 but is OK with 3.10

**Comment by albertbofill** [comment]
> ok @albertbofill this is confirmed. giswater plugin does not work with 3.14 but is OK with 3.10

@haubourg thanks for your work. We havn't tested yet our plugin with this new version of QGIS. As soon as we can, we'll check which is the problem with 3.14 and try to solve it to allow usage of the last version of QGIS.

**Comment by daviderill** [comment]
Close in #780
