### ISSUE TITLE
many manua pages can not scroll all the way

### ISSUE THREAD

**Issue by gubuntu** [Giswater/giswater_qgis_plugin#789]
Several pages in https://www.giswater.org/giswater-manual stop scroling before reaching the end, so there is no way to read the rest of the document

**Comment by albertbofill** [comment]
Hello @gubuntu , 
Please use https://giswater.gitbook.io/giswater-manual/ to consult the manual.
We've noticed that our website manual isn't working properly.

Soon we'll update website manual link to this brand new Gitbook manual.

Sorry for the inconvenience.

**Comment by gubuntu** [comment]
thanks for the quick response. Any chance you could respond to #787 too? Is QGIS 3.16 supported?

**Comment by albertbofill** [comment]
@gubuntu let me add that, if you'd like to start testing and using Giswater, better than our complete manual, I can recommend you to read firstly our Wiki on DB Model repository.

To begin easily I recommend:
https://github.com/Giswater/giswater_dbmodel/wiki/Getting-started
https://github.com/Giswater/giswater_dbmodel/wiki/Start-from-Scratch
