### ISSUE TITLE
error in creating schema

### ISSUE THREAD

**Issue by seabilwe** [Giswater/giswater_qgis_plugin#790]
I have been having issues with creating a schema, each time I create it I get this error:
![error_1](https://user-images.githubusercontent.com/56301949/113671794-22aee180-96b7-11eb-9c12-44aa10a1a7b5.PNG)
![Capture](https://user-images.githubusercontent.com/56301949/113671799-2478a500-96b7-11eb-85b0-ca838df1079d.PNG)

I repeated the whole installation process a couple of times from the guide: https://giswater.gitbook.io/giswater-manual/2.-installation-and-start-up, but I still  get the same outcome and at some instances QGIS 3.10 crashes when creating the schema.

**Comment by xtorret** [comment]
"Type raster does not exists"
It means that there is no extension of Postgis Raster activated., something like:
In some postGIS versions you need to activate with something like:
'CREATE EXTENSION postgis_raster'

**Comment by seabilwe** [comment]
Thank you @xtorret
