### ISSUE TITLE
GISWater toolbar button tips are wrong

### ISSUE THREAD

**Issue by gubuntu** [Giswater/giswater_qgis_plugin#791]
QGIS 3.10.4 on Windows

After opening a GISWater project

Toolbar buttons tips are '58_text', '206_text', etc

none of them have proper labels

**Comment by albertbofill** [comment]
That's because of the language of QGIS. We don't correctly manage it when it's not one of the languages we've translated. 
I'll tell the developers to fix it.
Thanks @gubuntu

**Comment by albertbofill** [comment]
@gubuntu you can try again with our last release 3.4.034. We've fixed it.

**Comment by gubuntu** [comment]
Thanks, this does fix it. The first time I loaded the previous version the burrons were correct, then they lost their descriptions. QGIS is using my locale which is en_za, i.e. English, not needing a translation.
