### ISSUE TITLE
Click on 'show info' button and QGIS hangs

### ISSUE THREAD

**Issue by gubuntu** [Giswater/giswater_qgis_plugin#792]
QGIS 3.10.4 on Windows

I load a giswater project and when I click on the giswater 'show info' button nothing happens and QGIS hangs

**Comment by albertbofill** [comment]
Can you give more information about what have you done before?
Show info button must be desactivated when the whole giswater plugin is loaded. It's use is only available without a giswater qgis project loaded.
![image](https://user-images.githubusercontent.com/34450054/113899081-bcb47e00-97cc-11eb-8621-ddbc65e5debb.png)
