### ISSUE TITLE
Apparent error with import from inp - Pump description

### ISSUE THREAD

**Issue by mcarvajalino** [Giswater/giswater_qgis_plugin#837]
Hi, 

First of all, thanks for the great work!. I am just starting with GISwater but have been trying to load an inp file from a (functioning) project and I am getting an SQL error that seems to say that the "Description" field for pumps is expected to be numeric (?). I have some informative texts there and they crash the import process. I am attaching an screenshot of the error message.
![image](https://user-images.githubusercontent.com/16334320/143249090-0aac45fe-d832-41df-8238-054af527543e.png)

**Comment by xtorret** [comment]
Hi @mcarvajalino,
Thank your for your interest in Giswater and for your words.
Import inp tool is on dev mode. Lots of data source options need to be managed. Let's solve yours.
We have two approach to solve this:

1. Check this wiki: https://github.com/Giswater/giswater_dbmodel/wiki/import-inp-file-debug-mode
2. Check the diferences againts sections [PUMPS] of your inp file and sections [PUMPS] from example inp file `plugins\giswater\resources\example\inp\swmm\swmm.inp` , and try to fit your [PUMPS] section with the example section wich it works!!!

I think this will solve your issue
Please keep informed!!!

**Comment by smaspons** [comment]
This issue hasn't had any activity in almost a year. If you wish to re-open it please add a comment here and we'll be happy to help.
