### ISSUE TITLE
Error while creating project

### ISSUE THREAD

**Issue by rcammi** [Giswater/giswater_qgis_plugin#897]
I am trying to create a project with example data

![image](https://github.com/Giswater/giswater_qgis_plugin/assets/62706597/c99df55d-4e62-404a-ab5b-ad10559f4b39)

but i keep getting this error 

![image](https://github.com/Giswater/giswater_qgis_plugin/assets/62706597/32b9753f-8961-47d0-ae98-af919b2867f8)

I have checked that postgis, pgrouting, and postgis_raster are correctly installed.

Working on:

PostgreSQL 10.22
QGIS 3.26.2
GISWATER 3.5.040

Can someone help me fix the error please, thank you.

**Comment by smaspons** [comment]
Hi @rcammi the error is due to the PostgreSQL version. It is highly recommended to use PostgreSQL 15, but 11 or higher should work.

Please, let us know if you have any more issues, thanks!

**Comment by rcammi** [comment]
It did work! Thank you. I was following the [user guide](https://giswater.gitbook.io/giswater_manual_es/2.-instalacion-y-puesta-en-marcha#2.2-descarga-y-configuracion-de-postgresql) where it says: 

"Hay distintas versiones disponibles (de psql) para descargar. Para trabajar con Giswater se necesita una versión entre la 9.5 y la 14."

Maybe I'm following an old guide but if not it could be updated! 

Thanks again.

**Comment by albertbofill** [comment]
You were following the correct guide, but it had not been updated for a while.
Postgres below 11 used to work for older giswater versions, but this is no longer true.
We have updated the user guide.
Thanks!
