### ISSUE TITLE
  Errore python : Impossible to load 'giswater' plug in due to initGui() method error. 

### ISSUE THREAD

**Issue by Eneko279** [Giswater/giswater_qgis_plugin#898]
Hi all,

My name is Eneko and I recently installed Qgis version 3.32.3, SWMM 5.2 and PostgreSQL 14.9.

I have seen that from Giswater manual it is recommended a previous versions of Qgis (3.22), but I  haven't been able to install.

Would you consider that this initGui()  error is due to QGis version ? How could I solve it ?

Thanks for your help,

Eneko.

**Comment by Eneko279** [comment]
Hi lads,

Problem solved with adequate Qgis version from here. https://download.osgeo.org/qgis/win64/

Thanks.
Eneko.

**Comment by smaspons** [comment]
Hi Eneko,

Yes, this is indeed a problem of the QGIS version, they changed some stuff in QGIS 3.30 that broke Giswater.

We are aware of this error and we will try to fix it as soon as possible.

Thank you,
Maspi.

**Comment by smaspons** [comment]
You can track the developement of the fix in this issue https://github.com/Giswater/giswater_qgis_plugin/issues/899

Thanks again!
Maspi.
